name: Build EXE

on:
  push:
    branches:
      - actions
  pull_request:
    branches:
      - actions

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller beautifulsoup4 selenium requests python-dotenv

    - name: Build EXE
      run: |
        pyinstaller --onefile --console main.py

    - name: Upload EXE
      uses: actions/upload-artifact@v3
      with:
        name: code_redeemer
        path: dist/main.exe